Header:
	Main Program:	8
	List Constants size:	2
	List class size:	8
	Size bytecode:	17
Constants:
		type:	5
		UID:1
		String:	(21)Constructor Hola Mon!
		type:	5
		UID:2
		String:	(18)Main del Hola Mon!
Class:
	UID:	1
	FatherUID:	0
	native?:	1
	name:	(7)Object
	Propieties (0):
	Methods (0):
	UID:	2
	FatherUID:	1
	native?:	1
	name:	(8)Boolean
	Propieties (0):
	Methods (3):
		UID:	1
		ByteCodeLine:	0
		Constructor:	0
		static?:	1
		Name:	(15)Boolean(Object)
		UID:	2
		ByteCodeLine:	0
		Constructor:	0
		static?:	0
		Name:	(12)and(Boolean)
		UID:	3
		ByteCodeLine:	0
		Constructor:	0
		static?:	0
		Name:	(11)or(Boolean)
	UID:	3
	FatherUID:	1
	native?:	1
	name:	(8)Integer
	Propieties (0):
	Methods (11):
		UID:	2
		ByteCodeLine:	0
		Constructor:	0
		static?:	1
		Name:	(15)Integer(Object)
		UID:	3
		ByteCodeLine:	0
		Constructor:	1
		static?:	0
		Name:	(15)Integer(String)
		UID:	4
		ByteCodeLine:	0
		Constructor:	0
		static?:	0
		Name:	(12)add(Integer)
		UID:	5
		ByteCodeLine:	0
		Constructor:	0
		static?:	0
		Name:	(12)sub(Integer)
		UID:	6
		ByteCodeLine:	0
		Constructor:	0
		static?:	0
		Name:	(12)mul(Integer)
		UID:	7
		ByteCodeLine:	0
		Constructor:	0
		static?:	0
		Name:	(12)div(Integer)
		UID:	8
		ByteCodeLine:	0
		Constructor:	0
		static?:	0
		Name:	(12)dif(Integer)
		UID:	9
		ByteCodeLine:	0
		Constructor:	0
		static?:	0
		Name:	(14)equal(Integer)
		UID:	10
		ByteCodeLine:	0
		Constructor:	0
		static?:	0
		Name:	(14)lower(Integer)
		UID:	11
		ByteCodeLine:	0
		Constructor:	0
		static?:	0
		Name:	(16)greater(Integer)
		UID:	12
		ByteCodeLine:	0
		Constructor:	0
		static?:	0
		Name:	(8)toString
	UID:	4
	FatherUID:	1
	native?:	1
	name:	(7)String
	Propieties (0):
	Methods (3):
		UID:	3
		ByteCodeLine:	0
		Constructor:	0
		static?:	1
		Name:	(14)String(Object)
		UID:	4
		ByteCodeLine:	0
		Constructor:	0
		static?:	0
		Name:	(11)add(String)
		UID:	5
		ByteCodeLine:	0
		Constructor:	0
		static?:	0
		Name:	(9)toInteger
	UID:	5
	FatherUID:	1
	native?:	1
	name:	(5)list
	Propieties (0):
	Methods (10):
		UID:	4
		ByteCodeLine:	0
		Constructor:	0
		static?:	1
		Name:	(12)list(Object)
		UID:	5
		ByteCodeLine:	0
		Constructor:	1
		static?:	0
		Name:	(4)list
		UID:	6
		ByteCodeLine:	0
		Constructor:	0
		static?:	0
		Name:	(12)get(Integer)
		UID:	7
		ByteCodeLine:	0
		Constructor:	0
		static?:	0
		Name:	(6)length
		UID:	8
		ByteCodeLine:	0
		Constructor:	0
		static?:	0
		Name:	(11)add(Object)
		UID:	9
		ByteCodeLine:	0
		Constructor:	0
		static?:	0
		Name:	(16)addFirst(Object)
		UID:	10
		ByteCodeLine:	0
		Constructor:	0
		static?:	0
		Name:	(5)first
		UID:	11
		ByteCodeLine:	0
		Constructor:	0
		static?:	0
		Name:	(11)removeFirst
		UID:	12
		ByteCodeLine:	0
		Constructor:	0
		static?:	0
		Name:	(4)last
		UID:	13
		ByteCodeLine:	0
		Constructor:	0
		static?:	0
		Name:	(3)pop
	UID:	6
	FatherUID:	1
	native?:	1
	name:	(5)File
	Propieties (0):
	Methods (4):
		UID:	5
		ByteCodeLine:	0
		Constructor:	0
		static?:	1
		Name:	(12)File(Object)
		UID:	6
		ByteCodeLine:	0
		Constructor:	1
		static?:	0
		Name:	(20)File(String, String)
		UID:	7
		ByteCodeLine:	0
		Constructor:	0
		static?:	0
		Name:	(13)write(String)
		UID:	8
		ByteCodeLine:	0
		Constructor:	0
		static?:	0
		Name:	(4)read
	UID:	7
	FatherUID:	1
	native?:	1
	name:	(6)Shell
	Propieties (0):
	Methods (4):
		UID:	6
		ByteCodeLine:	0
		Constructor:	0
		static?:	1
		Name:	(13)Shell(Object)
		UID:	7
		ByteCodeLine:	0
		Constructor:	0
		static?:	0
		Name:	(14)stdout(String)
		UID:	8
		ByteCodeLine:	0
		Constructor:	0
		static?:	0
		Name:	(5)stdin
		UID:	9
		ByteCodeLine:	0
		Constructor:	0
		static?:	0
		Name:	(14)stderr(String)
	UID:	8
	FatherUID:	1
	native?:	0
	name:	(11)helloWorld
	Propieties (0):
	Methods (3):
		UID:	7
		ByteCodeLine:	0
		Constructor:	0
		static?:	1
		Name:	(18)helloWorld(Object)
		UID:	8
		ByteCodeLine:	2
		Constructor:	1
		static?:	0
		Name:	(10)helloWorld
		UID:	9
		ByteCodeLine:	9
		Constructor:	0
		static?:	0
		Name:	(4)main
ByteCode:
	0:RET	-1	
	1:SIZE_INSTRUCTIONS	7	
	2:LOAD_CLASS	7	(Shell)
	3:LOAD_METHOD	7	(stdout(String))
	4:LOAD_CONSTANT	1	(Constructor Hola Mon!)
	5:CALL	1	(stdout(String))
	6:POP_TOP	0	
	7:RET	-1	
	8:SIZE_INSTRUCTIONS	8	
	9:PUSH_TOP	0	(reservant:i)
	10:LOAD_CLASS	7	(Shell)
	11:LOAD_METHOD	7	(stdout(String))
	12:LOAD_CONSTANT	2	(Main del Hola Mon!)
	13:CALL	1	(stdout(String))
	14:POP_TOP	0	
	15:RET	-1	
	16:SIZE_INSTRUCTIONS	9	
