# General defines

######################################################################

all: Index.pdf

Index.pdf: *.tex
	pdflatex Index.tex

clean: Index.pdf
	rm Index.loa Index.log Index.aux Index.lot Index.out Index.toc

